# File @generated by hack/generate-authors.sh.DO NOT EDIT.
# This file list all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

nyabingenorv <norvyphill@gmail.com>
DeborahAywa <debraokinda@gmail.com>
